name: PLAT DU JOUR SITE WEB CI/CD

on:
  push:
    branches:
      - dev
      - main
      - infra/devops
  pull_request:
    branches:
      - dev
      - main

  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sitepdj

jobs:

  # ============================================================
  # JOB 1 — BUILD & PUSH
  # ============================================================
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate short SHA
        id: vars
        run: echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' }}
          target: production
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHA_SHORT }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.title=sitepdj

  # ============================================================
  # JOB 2 — DEPLOY STAGING
  # Uniquement sur dev
  # ============================================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'
    environment:
      name: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get short SHA
        id: vars
        run: echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Copy compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: "docker/docker-compose.staging.yml, scripts/deploy.sh"
          target: ${{ vars.DEPLOY_PATH }}
          strip_components: 1

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io \
              -u "${{ github.repository_owner }}" --password-stdin

            cd ${{ vars.DEPLOY_PATH }}
            mv docker-compose.staging.yml docker-compose.yml
            chmod +x deploy.sh


            IMAGE_TAG=${{ steps.vars.outputs.SHA_SHORT }} \
              docker compose up -d --pull always sitepdj

           

  # ============================================================
  # JOB 3 — DEPLOY PRODUCTION
  # Uniquement sur main (merge depuis dev)
  # ============================================================
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get short SHA
        id: vars
        run: echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Copy compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: "docker/docker-compose.production.yml"
          target: ${{ vars.DEPLOY_PATH }}
          strip_components: 1

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io \
              -u "${{ github.repository_owner }}" --password-stdin

            cd ${{ vars.DEPLOY_PATH }}
            mv docker-compose.production.yml docker-compose.yml

            IMAGE_TAG=${{ steps.vars.outputs.SHA_SHORT }} \
              docker compose up -d --pull always sitepdj

            docker image prune -f